config/routes.rb
Rails.application.routes.draw do
  get 'calculations/new'

  root              'static_pages#home'
  get 'help' =>     'static_pages#help'
  get 'about' =>    'static_pages#about'

end

app/models/price_index.rb
class PriceIndex < ActiveRecord::Base
  belongs_to :region
  validates :region_id, presence: true
  validates :year, presence: true, uniqueness: { scope: :region } 
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :price_indices  #, dependent: destroy
	before_save { code.downcase! }
	validates :name, presence: true, length: { maximum: 255 }
	validates :code, presence: true, length: { maximum: 3 },
									 uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "CPI Worldwide"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar">
  <div class="container">
    <%=link_to "calculate cpi for any country", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "About",  about_path %></li>
      </ul>
    </nav>
  </div>
</header> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]> 
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<h3>About this page</h3>
<p>This page is created using the Consumer Price Index data gathered by the World Bank. Many nations offer an online CPI converter for their nation, but there is none that compares the values internationally.</p>
<p>
	For example, if you were born in Sweden, but you and your family currently live in Singapore, how does the pocketmoney given to you in 1990 compare to that of your children, today?
</p>
<p>
	The Worldwide CPI can answer such questions, and many more.
</p>

<h3>About the author</h3>
<p>
	This page was created by ylla using Ruby on Rails.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<h3>How to</h3>
<p>
	Select the year and the nations you wish to compare.
</p>
<p>
	Next, select the nation of the currency. For AUD, select Australia.
</p>
<p>
	Third, enter the monetary amount in the chosen currency. You don't need to specify for which year or country the amount is for, all possible values will be presented to you.
</p>
<p>
	Click the submit button.
</p>

<h3>Further questions</h3>
<p>
	If you have any further questions, feel free to contact <a href="http://www.github.com/ylla">ylla on github</a>.
</p>

app/views/static_pages/home.html.erb
<div class="narrow">
	<div class="center jumbotron">
		<h1>Global Consumer Price Index</h1>
      <form class="form-calculate">

				<p>Shortly you will be able to compare amounts between different years and currencies.</p>

				<p>Under construction. Please check back later.</p>
        <label for="inputRegion" class="sr-only">Region</label>
        <input type="text" id="inputRegion" class="form-control" placeholder="Sweden" required autofocus>
        <label for="inputAmount" class="sr-only">Amount</label>
        <input type="float" id="inputAmount" class="form-control" placeholder="100" required>
        
        <label for="year1" class="sr-only">Year 1</label>
        <input type="dateyear" id="year1" class="form-control" placeholder="2015" required>
        <label for="year2" class="sr-only">Year 2</label>
        <input type="dateyear" id="year2" class="form-control" placeholder="1960" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Calculate</button>
      </form>
	</div>
</div>